version: "3.8"

services:
  frontend:
    build: ./frontend
    container_name: bluemoon_frontend
    volumes:
      - fe_dist:/app/dist
    networks:
      - chatweb_chat-network

  backend:
    build: ./backend
    container_name: bluemoon_backend
    ports:
      - "5001:5001"
    env_file:
      - ./backend/.env
    environment:
      - PORT=5001
      - DB_SERVER=sqlserver
      - DB_NAME=...
      - DB_USER=...
      - DB_PASS=...
    volumes:
      - fe_dist:/app/frontend/dist:ro # Chia sẻ folder build của FE cho BE (read only)
      - ./backend/public:/app/public # Lưu ảnh, file...
    depends_on:
      - frontend
    networks:
      - chatweb_chat-network

networks:
  chatweb_chat-network:
    external: true

volumes:
  fe_dist:
